DEEPSEEK_API_TYPE: deepseek
DEEPSEEK_MODEL_NAME: deepseek-chat
DEEPSEEK_API_KEY: sk-blABC8urTBhDi9cr053dDc6c8a0644F19e2f06A3776d5282
DEEPSEEK_API_URL: "https://api.vveai.com/v1/"
############### settings ############
reflection_module: False # True or False
few_shot_num: 3 # 0 for zero-shot
episodes_num: 3 # run episodes
memory_path: 'memories/20_mem'
result_folder: 'results'

############ Highway-env config ############
simulation_duration: 20 # step
vehicle_count: 15
other_vehicle_type: "highway_env.vehicle.behavior.IDMVehicle" #other types are: "highway_env.vehicle.behavior.DefensiveVehicle" or "highway_env.vehicle.behavior.AggressiveVehicle"
vehicles_density: 2.0